### ISSUE TITLE
PadSwitcher64 C64 software doesn't appear to work on NTSC machines

### ISSUE THREAD

**Issue by misterblack1** [Hojo-Norem/PadSwitcher64#1]
Running the PRG, it asks to hit start and select on the control pad. When I do this, there is a slight flash on the screen and then a few seconds later it says "Communication Timeout with the interface!"

PadSiwtcher64 does work fine otherwise -- and pressing the button on joystick 2 enters a regular test screen and all the functions are working properly.

Is there anything I can do to troubleshoot? 

Adrian (from Adrian's Digital Basement)

**Comment by Hojo-Norem** [comment]
Hi.  The screen flash is a little debugging indicator.  The fact that it just
flashes and does not stick tells me that it is working to a degree.  It just
looks like that the effect that the difference in CPU clock speed between PAL
and NTSC is greater than I thought and the negotiation just times out sooner
on NTSC.

I've tripled the timeout length and attached the updated executable.  If it
works for you I'll update the GitHub.

[PadSwitcher64.zip](https://github.com/Hojo-Norem/PadSwitcher64/files/4970655/PadSwitcher64.zip)

**Comment by misterblack1** [comment]
Ok sorry for the delay in testing. Just gave it a try and sadly no luck!

https://www.youtube.com/watch?v=v7ZLdolSgAk&feature=youtu.be

Different but still a timeout. Incidentally I tested this machine using Sven's diagnostic test harness and it shows up as fully working (in case there might be a 6526 issue)

**Comment by Hojo-Norem** [comment]
Okay.  There should be no trouble with your hardware, it's just my underestimation of the differences between PAL and NTSC.  If there was HW issue then there's a good chance that the interfere would refuse to even begin handshaking and you would see no reaction at all on screen.

With the first version, did the border remain black or coloured after the flash?  A brief flash to black means there's a timeout during 'normal' communication while a solid white or red border means timeout during handshaking.

Try this build.  I had forgotten that there are three separate timeout checks in my code and I had gone and altered the wrong one!  

[PadSwitcher64.zip](https://github.com/Hojo-Norem/PadSwitcher64/files/4999527/PadSwitcher64.zip)

**Comment by misterblack1** [comment]
It was red -- check out the youtube video I posted there you can see it in action. :-)

Ok I'll try the next build and see.

**Comment by Hojo-Norem** [comment]
Thanks.  If it still does not work, keep an eye on the LED on the interface.  Depending on where the timeout is occurring, the LED will flash for roughly two seconds or roughly five seconds.

**Comment by misterblack1** [comment]
https://youtu.be/e2LAi0TGnCE

Hi unfortunately it's still not working. I used your updated 30th of July version and no visible change. See video. I also recorded what the LED is doing -- it's the two second flash.

**Comment by Hojo-Norem** [comment]
I think I'm getting down to the source of the problem, but at the moment I'm not much closer on a solution.

Compare what you see with what supposed to happen: https://youtu.be/BsXZNpseAn4

What is a flicker of a few dozen raster lines on my PAL machine is tens of frames on your NTSC model.  The short blink sequence on the interface tells me that the handshake is timing out on the interface side first.  I wonder if the 60Hz refresh and associated interrupts are fouling things up...

I'm going to re-write the communications section in assembly.  At least that way I can disable interrupts during communications and I can't be sure of how the compiled BASIC is behaving in NTSC land.

**Comment by Hojo-Norem** [comment]
Okay, re-write done.  It seems that the main issue stemmed from the C64 acting too quickly because even my poor attempt at 6502 machine code is faster than the compiled BASIC.  Fast enough that it broke until I put delays into the code.

Give this one a try.  If it does not work and the time-out border is CYAN, hit RUN/STOP+RESTORE as prompted then enter:
`POKE 50000,20`
`POKE 50001,64`
`POKE 50002,128`
`POKE 50003,5`
before typing RUN.  If it STILL does not work, re-type the last POKE, increase the 5 to 6 and re-RUN.

[PadSwitcher64.zip](https://github.com/Hojo-Norem/PadSwitcher64/files/5012663/PadSwitcher64.zip)

**Comment by Hojo-Norem** [comment]
Hi.  Any chance to try this version yet?

**Comment by misterblack1** [comment]
Hi!! Sorry I have just been so busy. Let me test it out right now. I'm intending to put out the video with your PadSwitcher64 this weekend, so it would be great to get this working for NTSC machines. :-)

**Comment by misterblack1** [comment]
Ok --- tried out your rewrite- There are 3 PRG files in the zip, so I tried all 3 and none work. Which one had the re-write you mention? So all of them give the red border -- haven't ever seen CYAN border with the timeouts. 

I tried the pokes on all 3 PRG files anyway up to 50003,7 with no luck. 

You know, just for fun let me try another C64 -- I think I've done all my testing on my ZIF64.. who knows maybe it has a fault or some kind?

**Comment by misterblack1** [comment]
Ok wow, I'm so sorry-- I just tried all 3 PRG files on another NTSC C64 (a shortboard this time.) The first two PRG files totally worked perfectly! The first one was pretty sluggish but the second ones worked fine too and wasn't slow. The third one worked on the first try -- but all subsequent tried give me communication error 159. The others work still -- I did get a CYAN border one time on the 2nd PRG but it worked every other time I tried it.

I also tried it with and without JaffyDos (a JiffyDos variant) and it seemed to make no difference.

 Let me break out a couple more machines to test on -- but how are you communicating with the MCU in the pad switcher? What might be causing it not work on my ZIF-64?

**Comment by misterblack1** [comment]
OK yes tried on a 3rd machine -- another breadbin same revision as my ZIF64 and it works fine too. So clearly something is faulty on my ZIF64 machine that's causing a problem. 

To summarize: PadSwitcher64.prg works reliably on NTSC machines. PadSwitcher64-basic.prg works too but is slow. PadSwitcher64unopt.prg does not work -- gives error 159 on both machines I tried. (It did work just one time.)

Sorry for making you chase all these issues when my C64 may have been the issue all along!!

**Comment by Hojo-Norem** [comment]
The C64 > MCU communications relies on the fact that the control port lines are just essentially programmable IO lines connected to one of the CIAs.  All I do is set some of them to output and use them to talk to the MCU.  Some C64 board revisions have direct connections from the CIA to the control ports while others have various filtering components on the lines, like my short board C64 that I developed the PadSwitcher on.

The PadSwitcher64.prg software is essentially compiled BASIC with a little handwritten assembly.  PadSwitcher64-basic is the exact same but uncompiled and therefore slow while PadSwitcher64-unopt is compiled but without any of the compilers optimisations turned on.

**Comment by misterblack1** [comment]
Ah cool! Makes sense. I must have faulty 6526 chip(s) on my ZIF64 machine. Luckily both chips are socketed so I should be able to figure out what is bad. 

So I'd say time to update your readme if you haven't already to say it works with NTSC machines too! Thank you for the great project!

**Comment by Kalidomra** [comment]
Using an NTSC 64C, I was only able to get it to work using the last posted prg with the POKE statements and using POKE 50003,8. However initially when pressing the start and select, I need to hold it down for a few seconds.
